table Clientes
	lineageTag: 32622a8f-682b-4352-ad71-a1a10050cd0c

	column 'ID Cliente'
		dataType: string
		lineageTag: 21398560-7867-43bc-b57d-7567cafe5f5b
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: 85f83f74-3eec-4568-81c5-c27a1b9c800b
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: a79104ff-18c8-4f23-ab7d-413a4081752c
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 1acf5ec6-7433-4299-89c0-433f6b7cef2c
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: b7bb96ce-9c04-49a5-8355-dd8409c7ddf8
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 1816b2ce-459a-4afe-baf2-1b1da73a23b2
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Mercado
		dataType: string
		lineageTag: d1fecc21-fbbd-42da-9c58-e6b6775b2faa
		summarizeBy: none
		sourceColumn: Mercado

		annotation SummarizationSetBy = Automatic

	column Regiao
		dataType: string
		lineageTag: bb625ec0-98ca-4cdd-ac16-9fce206f7727
		summarizeBy: none
		sourceColumn: Regiao

		annotation SummarizationSetBy = Automatic

	partition Clientes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\deeh_\OneDrive\Documentos\Clientes.csv.xlsx"), null, true),
				    Clientes_Sheet = Fonte{[Item="Clientes",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Clientes_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Cliente", type text}, {"Nome Cliente", type text}, {"Segmento", type text}, {"Cidade", type text}, {"Estado", type text}, {"Pais", type text}, {"Mercado", type text}, {"Regiao", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

