table Produtos
	lineageTag: b35e0e83-b9e4-4289-8b80-25d6bf07b213

	column 'ID Produto'
		dataType: string
		lineageTag: 12631662-739f-4f4b-abfd-bdfa5536d23e
		summarizeBy: none
		sourceColumn: ID Produto

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: c4771460-ec63-429b-a250-7ddff309d6b4
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column SubCategoria
		dataType: string
		lineageTag: 3f72649b-ff35-4020-8da5-2e8476f5b684
		summarizeBy: none
		sourceColumn: SubCategoria

		annotation SummarizationSetBy = Automatic

	column 'Nome Produto'
		dataType: string
		lineageTag: 1415605a-83d3-4ad1-93cb-dc331dc3f82c
		summarizeBy: none
		sourceColumn: Nome Produto

		annotation SummarizationSetBy = Automatic

	partition Produtos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\deeh_\OneDrive\Documentos\Produtos.csv.xlsx"), null, true),
				    Produtos_Sheet = Fonte{[Item="Produtos",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Produtos_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Produto", type text}, {"Categoria", type text}, {"SubCategoria", type text}, {"Nome Produto", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1")
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

