table Vendas
	lineageTag: 4a49cbf2-802c-4a4c-931b-b53a4359da9c

	column Pedido
		dataType: string
		lineageTag: 457aaac4-4fa8-44d1-968a-d31d3fe4c474
		summarizeBy: none
		sourceColumn: Pedido

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: b4518a3f-b7c9-45d6-9657-7d28fed15b27
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 86f5f22e-7658-4704-89a9-56eed3161169
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Valor Venda'
		dataType: double
		lineageTag: 6aec75f7-ed44-4744-9f0a-0eaa34135009
		summarizeBy: sum
		sourceColumn: Valor Venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantidade Vendida'
		dataType: int64
		formatString: 0
		lineageTag: 98dd578b-468b-48b6-9dba-c66668474df1
		summarizeBy: sum
		sourceColumn: Quantidade Vendida

		annotation SummarizationSetBy = Automatic

	column 'Custo Envio'
		dataType: double
		lineageTag: c8634197-c1a0-40b4-893c-f09012dae06a
		summarizeBy: sum
		sourceColumn: Custo Envio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lucro = Vendas[Valor Venda]-Vendas[Custo Envio]
		lineageTag: bedaca1e-cb48-42ca-b425-81c67fce27fc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MaergemLucro = ROUND( DIVIDE(Vendas[Lucro],Vendas[Valor Venda]) *100,2)
		lineageTag: 9826da53-dfcd-443c-ac03-c9fe8f35b8b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\deeh_\OneDrive\Documentos\Vendas.csv.xlsx"), null, true),
				    Vendas_Sheet = Fonte{[Item="Vendas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Vendas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Pedido", type text}, {"Cliente", type text}, {"Produto", type text}, {"Valor Venda", type number}, {"Quantidade Vendida", Int64.Type}, {"Custo Envio", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

